import { createHash, randomBytes } from "node:crypto";
import { mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import {
  assertScope,
  assertStableId,
  assertText,
  type LearningRecord,
  type LearningScope,
} from "./contracts.ts";
import type { LearningCoreStorage } from "./storage.ts";

export type VaultProjectionReceipt = {
  learning_id: string;
  learning_version: number;
  relative_path: string;
  sha256: string;
  generated: true;
  authoritative: false;
  generated_at: string;
};

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function renderFrontmatterList(items: string[]): string {
  return items.length === 0 ? "  []" : items.map((item) => `  - ${yamlString(item)}`).join("\n");
}

export function renderLearningNote(learning: LearningRecord, generatedAt: string): string {
  const supportLinks = learning.supporting_evidence.map((item) => `[[${item.evidence_id}]]`);
  const counterLinks = learning.counterevidence.map((item) => `[[${item.evidence_id}]]`);
  const limitationLines = learning.limitations.map((item) => `- ${item}`).join("\n");
  return `---
id: ${yamlString(learning.learning_id)}
type: ${yamlString("negroni-learning")}
generated: true
authoritative: false
owner_id: ${yamlString(learning.owner_id)}
workspace_id: ${yamlString(learning.workspace_id)}
brand_id: ${yamlString(learning.brand_id)}
version: ${learning.version}
state: ${yamlString(learning.state)}
confidence: ${learning.confidence}
approval_state: ${yamlString(learning.approval_state)}
provenance: ${yamlString(learning.provenance)}
applicability: ${yamlString(learning.applicability)}
freshness: ${yamlString(learning.updated_at)}
generated_at: ${yamlString(generatedAt)}
supporting_evidence:
${renderFrontmatterList(supportLinks)}
counterevidence:
${renderFrontmatterList(counterLinks)}
---

# ${learning.statement}

> [!important] Database-authoritative projection
> This note was generated by Negroni from Learning Core version ${learning.version}. Edit through a validated human-revision import; direct edits are not authoritative.

## Statement

${learning.statement}

## Applicability

${learning.applicability}

## Limitations

${limitationLines || "- No limitations were recorded."}

## Evidence

Supporting: ${supportLinks.join(", ") || "None recorded"}

Counterevidence: ${counterLinks.join(", ") || "None recorded"}

## Provenance

${learning.provenance}
`;
}

export class ObsidianVaultProjector {
  readonly #store: LearningCoreStorage;

  constructor(store: LearningCoreStorage) {
    this.#store = store;
  }

  async project(scope: LearningScope, learningId: string): Promise<VaultProjectionReceipt> {
    const checked = assertScope(scope);
    const id = assertStableId(learningId, "learning_id");
    const learning = this.#store.getLearning(checked, id);
    if (!learning) throw new Error("Learning was not found in the requested scope.");
    const previous = this.#store.getVaultProjection(checked, id);
    const generatedAt = previous?.version === learning.version ? previous.generated_at : this.#store.now();
    const contents = renderLearningNote(learning, generatedAt);
    const bytes = Buffer.from(contents, "utf8");
    const sha256 = createHash("sha256").update(bytes).digest("hex");
    const relativePath = `learnings/${id}.md`;
    const destination = resolve(this.#store.vaultRoot, relativePath);
    if (previous) {
      try {
        const existing = await readFile(destination);
        const existingHash = createHash("sha256").update(existing).digest("hex");
        if (existingHash !== previous.sha256) {
          throw new Error("Generated vault note has human edits; import them for review before projecting a new version.");
        }
        if (previous.version === learning.version && existingHash === sha256) {
          return {
            learning_id: id,
            learning_version: learning.version,
            relative_path: relativePath,
            sha256,
            generated: true,
            authoritative: false,
            generated_at: generatedAt,
          };
        }
      } catch (error) {
        if (!(error && typeof error === "object" && "code" in error && error.code === "ENOENT")) throw error;
      }
    }
    await mkdir(dirname(destination), { recursive: true, mode: 0o700 });
    const temporary = `${destination}.tmp-${process.pid}-${randomBytes(6).toString("hex")}`;
    await writeFile(temporary, bytes, { flag: "wx", mode: 0o600 });
    await rename(temporary, destination);
    await stat(destination);
    this.#store.recordVaultProjection({
      ...checked,
      learning_id: id,
      version: learning.version,
      relative_path: relativePath,
      sha256,
      generated_at: generatedAt,
    });
    return {
      learning_id: id,
      learning_version: learning.version,
      relative_path: relativePath,
      sha256,
      generated: true,
      authoritative: false,
      generated_at: generatedAt,
    };
  }

  importHumanRevision(scope: LearningScope, note: string): { import_id: string; status: "pending_review" } {
    const checked = assertScope(scope);
    const bounded = assertText(note, "note", 50_000);
    const frontmatterMatch = bounded.match(/^---\n([\s\S]*?)\n---\n/);
    if (!frontmatterMatch) throw new Error("Human revision requires YAML frontmatter.");
    const fields = new Map<string, string>();
    for (const line of frontmatterMatch[1]?.split("\n") ?? []) {
      const match = line.match(/^([a-z_]+):\s*(.+)$/);
      if (match?.[1] && match[2]) fields.set(match[1], match[2].replace(/^"|"$/g, ""));
    }
    if (fields.get("generated") !== "false") throw new Error("Human revision must set generated: false.");
    const learningId = assertStableId(fields.get("revision_of"), "revision_of");
    if (fields.get("owner_id") !== checked.owner_id || fields.get("workspace_id") !== checked.workspace_id
      || fields.get("brand_id") !== checked.brand_id) {
      throw new Error("Human revision scope does not match the requested Learning Core scope.");
    }
    const baseVersion = Number(fields.get("base_version"));
    if (!Number.isInteger(baseVersion) || baseVersion < 1) throw new Error("base_version is invalid.");
    const statementMatch = bounded.match(/\n## Proposed statement\n\n([^\n][\s\S]*?)(?:\n\n## |\n*$)/);
    if (!statementMatch?.[1]) throw new Error("Human revision requires a Proposed statement section.");
    const proposedStatement = assertText(statementMatch[1].trim(), "proposed_statement");
    const noteHash = createHash("sha256").update(bounded).digest("hex");
    const importId = `revision_${noteHash.slice(0, 20)}`;
    return this.#store.recordHumanRevision({
      ...checked,
      import_id: importId,
      learning_id: learningId,
      base_version: baseVersion,
      proposed_statement: proposedStatement,
      note_sha256: noteHash,
    });
  }
}
